#!/bin/bash
vpc_name=${1}
subnet_num=${2}
#touch f1
for (( i=1; i<=2; i++))
do
        for (( j=1; j<=${subnet_num}; j++))
        do
        ip link add vethE${i}I${j} type veth peer name vethI${i}E${j}
        pid=`docker inspect -f {{.State.Pid}} ${vpc_name}EGW${i}`
        ip link set vethE${i}I${j} netns ${pid}

        pid=`docker inspect -f {{.State.Pid}} ${vpc_name}IGW${j}`
        if [ ! -L /var/run/netns/${vpc_name}IGW${j} ]; then
                #echo "aaaaaa"
                ln -s /proc/${pid}/ns/net /var/run/netns/${vpc_name}IGW${j}
        fi
        ip link set vethI${i}E${j} netns ${pid}
        ip netns exec ${vpc_name}EGW${i} ip addr add  ${i}${j}.0.0.1/24 dev vethE${i}I${j}
    	ip netns exec ${vpc_name}IGW${j} ip addr add ${i}${j}.0.0.2/24 dev vethI${i}E${j}
        ip netns exec ${vpc_name}EGW${i} ip link set  vethE${i}I${j} up
        ip netns exec ${vpc_name}IGW${i} ip link set  vethI${i}E${j} up
        echo -e "  neighbor ${i}${j}.0.0.2 remote-as 100 \n  network ${i}${j}.0.0.0/24" >> /root/playbook_logs/bgpFiles/bgpd${vpc_name}EGW${i}.conf
        echo -e "  neighbor ${i}${j}.0.0.1 remote-as 100 \n  network ${i}${j}.0.0.0/24" >> /root/playbook_logs/bgpFiles/bgpd${vpc_name}IGW${j}.conf
        
        done

   	#docker cp /root/bgpFiles/bgpd${vpc_name}EGW${i}.conf ${vpc_name}EGW${i}:/etc/quagga/bgpd.conf
   	#docker exec ${vpc_name}EGW${i} chown quagga:quagga /etc/quagga/bgpd.conf 
	#docker exec ${vpc_name}EGW${i} /usr/lib/quagga/quagga restart
        
done
                

